import type { Church } from "./data.types"

export const CHURCHES: Church[] = [
  {
    id: "grace-independent-baptist-church",
    name: "Grace Independent Baptist Church",
    pastor: "Dennis Osueke",
    country: "Nigeria",
    region: null,
    city: null,
    contact: "+234-708-2696",
  },
  {
    id: "fellowship-baptist-church",
    name: "Fellowship Baptist Church",
    pastor: "Abraham Oluwatosin",
    country: "Nigeria",
    region: null,
    city: "Akure",
    contact: "+234-706-463-4434",
  },
  {
    id: "fundamental-baptist-church-of-mamponteng",
    name: "Fundamental Baptist Church of Mamponteng",
    pastor: "Kingsley Addai",
    country: "Ghana",
    region: "Ashanti",
    city: "Mamponteng",
    contact: "024-395-1036",
  },
  {
    id: "city-baptist-church",
    name: "City Baptist Church",
    pastor: "David Owusu",
    country: "Ghana",
    region: "Ashanti",
    city: "Agric, Kumasi",
    contact: null,
  },
  {
    id: "fundamental-baptist-church-offinso",
    name: "Fundamental Baptist Church",
    pastor: "Otchere Boachie",
    country: "Ghana",
    region: "Ashanti",
    city: "Offinso",
    contact: null,
  },
  {
    id: "fundamental-baptist-church-of-petrensa",
    name: "Fundamental Baptist Church of Petrensa",
    pastor: "Isaac Owusu Ansah",
    country: "Ghana",
    region: "Ashanti",
    city: "Petrensa",
    contact: "055-527-3909",
  },
  {
    id: "fundamental-baptist-church-kunsu",
    name: "Fundamental Baptist Church",
    pastor: "Michael Naab",
    country: "Ghana",
    region: "Ashanti",
    city: "Kunsu",
    contact: null,
  },
  {
    id: "fundamental-baptist-church-of-foase",
    name: "Fundamental Baptist Church of Foase",
    pastor: "Gyasi Boateng",
    country: "Ghana",
    region: "Ashanti",
    city: "Foase, Kumasi",
    contact: "054-834-5476",
  },
  {
    id: "calvary-independent-baptist-church",
    name: "Calvary Independent Baptist Church",
    pastor: "Samson Laniran",
    country: "Ghana",
    region: "Ashanti",
    city: "Ayiaya (Tech Area), Kumasi",
    contact: "024-480-6293",
  },
  {
    id: "fundamental-baptist-church-of-kuntenase",
    name: "Fundamental Baptist Church of Kuntenase",
    pastor: "Jonas Osei-Owusu",
    country: "Ghana",
    region: "Ashanti",
    city: "Kuntanase",
    contact: "020-786-2696",
  },
  {
    id: "faith-baptist-church",
    name: "Faith Baptist Church",
    pastor: "Maxwell Donkor",
    country: "Ghana",
    region: "Ashanti",
    city: "Sepaase",
    contact: "024-412-3036",
  },
  {
    id: "fundamental-baptist-church-of-fiapre",
    name: "Fundamental Baptist Church of Fiapre",
    pastor: "Rexford Anning",
    country: "Ghana",
    region: "Bono",
    city: "Sunyani",
    contact: "024-276-7840",
  },
  {
    id: "salvation-baptist-church",
    name: "Salvation Baptist Church",
    pastor: "Abraham Subui",
    country: "Ghana",
    region: "Bono East",
    city: "Nkwanta",
    contact: "027-664-1427",
  },
  {
    id: "new-life-baptist-church",
    name: "New Life Baptist Church",
    pastor: "Isaac Otwey",
    country: "Ghana",
    region: "Central",
    city: "Mamford",
    contact: "055-527-3909",
  },
  {
    id: "berean-baptist-church",
    name: "Berean Baptist Church",
    pastor: "Isaac Boateng",
    country: "Ghana",
    region: "Greater Accra",
    city: "Accra",
    contact: "027-433-9549",
  },
]
