/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PastorRouteImport } from './routes/pastor'
import { Route as MinistriesRouteImport } from './routes/ministries'
import { Route as HeavenRouteImport } from './routes/heaven'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConferencesRouteImport } from './routes/conferences'
import { Route as CollegeRouteImport } from './routes/college'
import { Route as ChurchesRouteImport } from './routes/churches'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ResourcesDiscipleshipRouteImport } from './routes/resources/discipleship'
import { Route as ProjectsFundedRouteImport } from './routes/projects/funded'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/project.$id'

const PastorRoute = PastorRouteImport.update({
  id: '/pastor',
  path: '/pastor',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesRoute = MinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => rootRouteImport,
} as any)
const HeavenRoute = HeavenRouteImport.update({
  id: '/heaven',
  path: '/heaven',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesRoute = ConferencesRouteImport.update({
  id: '/conferences',
  path: '/conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeRoute = CollegeRouteImport.update({
  id: '/college',
  path: '/college',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurchesRoute = ChurchesRouteImport.update({
  id: '/churches',
  path: '/churches',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesDiscipleshipRoute = ResourcesDiscipleshipRouteImport.update({
  id: '/resources/discipleship',
  path: '/resources/discipleship',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsFundedRoute = ProjectsFundedRouteImport.update({
  id: '/projects/funded',
  path: '/projects/funded',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/project/$id',
  path: '/projects/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/churches': typeof ChurchesRoute
  '/college': typeof CollegeRoute
  '/conferences': typeof ConferencesRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/heaven': typeof HeavenRoute
  '/ministries': typeof MinistriesRoute
  '/pastor': typeof PastorRoute
  '/projects/funded': typeof ProjectsFundedRoute
  '/resources/discipleship': typeof ResourcesDiscipleshipRoute
  '/projects/': typeof ProjectsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/projects/project/$id': typeof ProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/churches': typeof ChurchesRoute
  '/college': typeof CollegeRoute
  '/conferences': typeof ConferencesRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/heaven': typeof HeavenRoute
  '/ministries': typeof MinistriesRoute
  '/pastor': typeof PastorRoute
  '/projects/funded': typeof ProjectsFundedRoute
  '/resources/discipleship': typeof ResourcesDiscipleshipRoute
  '/projects': typeof ProjectsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/projects/project/$id': typeof ProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/churches': typeof ChurchesRoute
  '/college': typeof CollegeRoute
  '/conferences': typeof ConferencesRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/heaven': typeof HeavenRoute
  '/ministries': typeof MinistriesRoute
  '/pastor': typeof PastorRoute
  '/projects/funded': typeof ProjectsFundedRoute
  '/resources/discipleship': typeof ResourcesDiscipleshipRoute
  '/projects/': typeof ProjectsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/projects/project/$id': typeof ProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/churches'
    | '/college'
    | '/conferences'
    | '/contact'
    | '/donate'
    | '/heaven'
    | '/ministries'
    | '/pastor'
    | '/projects/funded'
    | '/resources/discipleship'
    | '/projects/'
    | '/resources/'
    | '/projects/project/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/churches'
    | '/college'
    | '/conferences'
    | '/contact'
    | '/donate'
    | '/heaven'
    | '/ministries'
    | '/pastor'
    | '/projects/funded'
    | '/resources/discipleship'
    | '/projects'
    | '/resources'
    | '/projects/project/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/churches'
    | '/college'
    | '/conferences'
    | '/contact'
    | '/donate'
    | '/heaven'
    | '/ministries'
    | '/pastor'
    | '/projects/funded'
    | '/resources/discipleship'
    | '/projects/'
    | '/resources/'
    | '/projects/project/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChurchesRoute: typeof ChurchesRoute
  CollegeRoute: typeof CollegeRoute
  ConferencesRoute: typeof ConferencesRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  HeavenRoute: typeof HeavenRoute
  MinistriesRoute: typeof MinistriesRoute
  PastorRoute: typeof PastorRoute
  ProjectsFundedRoute: typeof ProjectsFundedRoute
  ResourcesDiscipleshipRoute: typeof ResourcesDiscipleshipRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pastor': {
      id: '/pastor'
      path: '/pastor'
      fullPath: '/pastor'
      preLoaderRoute: typeof PastorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries': {
      id: '/ministries'
      path: '/ministries'
      fullPath: '/ministries'
      preLoaderRoute: typeof MinistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heaven': {
      id: '/heaven'
      path: '/heaven'
      fullPath: '/heaven'
      preLoaderRoute: typeof HeavenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences': {
      id: '/conferences'
      path: '/conferences'
      fullPath: '/conferences'
      preLoaderRoute: typeof ConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college': {
      id: '/college'
      path: '/college'
      fullPath: '/college'
      preLoaderRoute: typeof CollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/churches': {
      id: '/churches'
      path: '/churches'
      fullPath: '/churches'
      preLoaderRoute: typeof ChurchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/discipleship': {
      id: '/resources/discipleship'
      path: '/resources/discipleship'
      fullPath: '/resources/discipleship'
      preLoaderRoute: typeof ResourcesDiscipleshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/funded': {
      id: '/projects/funded'
      path: '/projects/funded'
      fullPath: '/projects/funded'
      preLoaderRoute: typeof ProjectsFundedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/project/$id': {
      id: '/projects/project/$id'
      path: '/projects/project/$id'
      fullPath: '/projects/project/$id'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChurchesRoute: ChurchesRoute,
  CollegeRoute: CollegeRoute,
  ConferencesRoute: ConferencesRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  HeavenRoute: HeavenRoute,
  MinistriesRoute: MinistriesRoute,
  PastorRoute: PastorRoute,
  ProjectsFundedRoute: ProjectsFundedRoute,
  ResourcesDiscipleshipRoute: ResourcesDiscipleshipRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
